//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Winscope.rc
//
#define IDD_ABOUTBOX                    100
#define ID_SCOPE_STATE                  101
#define ID_SCOPE_DEBUG_STATE            102
#define ID_DG_MOUSE_POINT               103
#define IDD_SAMPLING                    106
#define IDD_FORMAT                      107
#define IDD_TRIGGER                     108
#define IDD_SAMPLE_LOGGING              109
#define IDR_MAINFRAME                   128
#define IDR_WINSCOTYPE                  129
#define IDD_TEST_DLG                    130
#define IDD_TEMP_PROGRESS               131
#define IDD_BUFFER_SETTING              132
#define IDC_STATUS                      1000
#define IDC_EDIT1                       1000
#define IDC_PRB_TRG_LVL_A_VOLT          1000
#define IDC_START_THREAD                1001
#define IDC_EDIT2                       1001
#define IDC_BUF_SIZE_SLIDER             1001
#define IDC_PRB_TRG_LVL_B_VOLT          1001
#define IDC_LOOP_ABORT                  1002
#define IDC_TRIG_DELY_SLIDER            1002
#define IDC_PRB_TRG_LVL_A2              1002
#define IDC_PRB_TRG_LVL_A               1002
#define IDC_TRIGGER_DELAY               1003
#define IDC_PRB_TRG_LVL_B2              1003
#define IDC_PRB_TRG_LVL_B               1003
#define IDC_A_VPERDIV                   1004
#define IDC_A_INPUT                     1005
#define IDC_COMBO1                      1006
#define IDC_A_I_AC                      1006
#define IDC_TRIGG_FUNCTION              1006
#define IDC_VIEW_RADIX                  1006
#define IDC_A_I_GND                     1007
#define IDC_RADIO1                      1008
#define IDC_B_VPERDIV                   1008
#define IDC_PRB_TRIGG_SRC               1008
#define IDC_RADIO2                      1009
#define IDC_B_INPUT                     1009
#define IDC_PRB_TRIGG_SRC_B             1009
#define IDC_RADIO3                      1010
#define IDC_B_I_AC                      1010
#define IDC_PRB_TRIGG_SLOPE             1010
#define IDC_RADIO4                      1011
#define IDC_B_I_GND                     1011
#define IDC_PRB_TRIGG_SLOPE_NEG         1011
#define IDC_RADIO5                      1012
#define IDC_CLOCK_SEL_EXT               1012
#define IDC_EXT_PRB_TRIGG_SLOPE         1012
#define IDC_RADIO6                      1013
#define IDC_TPERDIV                     1013
#define IDC_EXT_PRB_TRIGG_SLOPE_NEG     1013
#define IDC_COMBO2                      1014
#define IDC_SM_NORMAL                   1014
#define IDC_PTRN_SYMBOL                 1014
#define IDC_COMBO3                      1015
#define IDC_BUFFER_SIZE                 1015
#define IDC_PTRN_RADIX                  1015
#define IDC_COMBO5                      1016
#define IDC_CLOCK_SELECTION             1016
#define IDC_LABEL_NAME                  1016
#define IDC_EDGE_SYMBOL                 1016
#define IDC_RADIO8                      1017
#define IDC_LABEL_LIST                  1017
#define IDC_SYMBOL_EDGE                 1017
#define IDC_RADIO9                      1018
#define IDC_REMOVE_LABEL                1018
#define IDC_SYMBOL_EDGE_NEG             1018
#define IDC_SM_AUTO                     1019
#define IDC_ADD_LABEL                   1019
#define IDC_SWEEP_MODE                  1020
#define IDC_MODIFY_LABEL                1020
#define IDC_SYMBIT_P7                   1021
#define IDC_CHECK1                      1022
#define IDC_TRIGG_PTRN                  1022
#define IDC_SCROLLBAR1                  1023
#define IDC_SYMBIT_P6                   1023
#define IDC_LVL_A_SCROLLBAR             1023
#define IDC_PROGRESS                    1023
#define IDC_SCROLLBAR2                  1024
#define IDC_SYMBIT_P5                   1024
#define IDC_LVL_B_SCROLLBAR             1024
#define IDC_NON_SWEEP_SETTINGS          1024
#define IDC_EDIT3                       1025
#define IDC_SYMBIT_P4                   1025
#define IDC_EDIT4                       1026
#define IDC_SYMBIT_P3                   1026
#define IDC_EDIT5                       1027
#define IDC_SYMBIT_P2                   1027
#define IDC_SYMBIT_P1                   1028
#define IDC_SYMBIT_P0                   1029
#define IDC_PRB_A_ACTIVE                1030
#define IDC_SYMBIT_Q7                   1031
#define IDC_COMBO6                      1032
#define IDC_SYMBIT_Q6                   1032
#define IDC_BUTTON4                     1033
#define IDC_SYMBIT_Q5                   1033
#define IDC_SYMBIT_Q4                   1034
#define IDC_SYMBIT_Q3                   1035
#define IDC_SYMBIT_Q2                   1036
#define IDC_SYMBIT_Q1                   1037
#define IDC_SYMBIT_Q0                   1038
#define IDC_PRB_B_ACTIVE                1039
#define IDC_POD_P_ACTIVE                1040
#define IDC_POD_Q_ACTIVE                1041
#define ID_VIEW_WINSCOPE_CONTROL_WINDOW 32771
#define ID_HW_CONFIGUREHARDWARE         32772
#define ID_HW_SELECTCONFIGURATIONFILE   32773
#define ID_HW_GETFWVERSIONS             32774
#define ID_HW_STARTINFINITELOOPINTHREAD 32775
#define ID_SCOPE_CLAIMSCOPEOWNERSHIP    32776
#define ID_SCOPE_RUNSCOPE               32777
#define ID_SCOPE_STOPSCOPE              32778
#define ID_SCOPE_QUERYSWEEPSTATE        32782
#define ID_SCOPE_DRAWWITHDOTS           32784
#define ID_SCOPE_NOERASE                32785
#define ID_VIEW_ZOOMIN                  32791
#define ID_VIEW_ZOOMOUT                 32792
#define ID_VIEW_FITALL                  32793
#define ID_VIEW_NOZOOM                  32794
#define ID_VIEW_CORSORX                 32795
#define ID_VIEW_CURSORY                 32796
#define ID_VIEW_CURSORX                 32797
#define ID_VIEW_VOLTAGECURSORA          32798
#define ID_VIEW_VOLTAGECURSORB          32799
#define ID_FILE_EXPORTTOCSV             32804
#define ID_FILE_EXPORTTOMETAFILE        32805
#define ID_VIEW_DISPLAYGRID             32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
